// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Sanitize env values: strip whitespace AND wrapping quotes. Values pasted
  // into dashboards (e.g. Vercel) as "https://..." — with literal quotes —
  // are a real-world cause of supabase-js "Invalid supabaseUrl".
  const clean = (v: string | undefined) =>
    (v ?? '').trim().replace(/^["']+|["']+$/g, '').trim();

  // On the SERVER, prefer the RUNTIME process.env so a changed backend takes
  // effect without a fresh client rebuild (the VITE_* values are inlined at
  // build time and can be stale). In the BROWSER, only the build-time VITE_*
  // values exist.
  const isServer = typeof window === 'undefined';
  const pick = (viteVal: string | undefined, procVal: string | undefined) =>
    isServer ? procVal || viteVal : viteVal;

  const SUPABASE_URL = clean(pick(import.meta.env.VITE_SUPABASE_URL, process.env.SUPABASE_URL));
  const SUPABASE_PUBLISHABLE_KEY = clean(
    pick(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, process.env.SUPABASE_PUBLISHABLE_KEY),
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL / VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in your host (e.g. Vercel → Settings → Environment Variables) and redeploy.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Fail with an actionable message rather than the cryptic supabase-js
  // "Invalid supabaseUrl" when the value isn't a full http(s) URL.
  if (!/^https?:\/\//i.test(SUPABASE_URL)) {
    const message = `Invalid SUPABASE_URL: "${SUPABASE_URL}". Use the full project URL, e.g. https://YOUR-REF.supabase.co (with https://, no quotes/trailing slash).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

