// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resolvePublicSupabaseConfig } from '@/lib/supabase-config';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // On the SERVER, prefer the RUNTIME process.env so a changed backend takes
  // effect without a fresh client rebuild (the VITE_* values are inlined at
  // build time and can be stale). In the BROWSER, only the build-time VITE_*
  // values exist. resolvePublicSupabaseConfig() then cleans the values
  // (whitespace/quotes) and falls back to the built-in project config when
  // the env is missing, malformed, or points at the retired backend.
  const isServer = typeof window === 'undefined';
  const pick = (viteVal: string | undefined, procVal: string | undefined) =>
    isServer ? procVal || viteVal : viteVal;

  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = resolvePublicSupabaseConfig(
    pick(import.meta.env.VITE_SUPABASE_URL, process.env.SUPABASE_URL),
    pick(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, process.env.SUPABASE_PUBLISHABLE_KEY),
  );

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

